#!/bin/sh

export LANG=c

image=$1
DATA_DIR=$2
LOGS_DIR=$DATA_DIR/logs

if [ "$LOGS_DIR" != "" ] && [ -d $LOGS_DIR ]; then
	log=$LOGS_DIR/fbv.log
else
	log=/dev/null
fi

cat /dev/zero > /dev/fb0 2>/dev/null;
/usr/local/bin/fbv -quickfe $image 2>&1 >> $log
