#!/bin/sh

export LANG=c

image=$1
DATA_DIR=$2
LOGS_DIR=$DATA_DIR/logs
RES_DIR=$DATA_DIR/resources

if [ "$LOGS_DIR" != "" ] && [ -d $LOGS_DIR ]; then
	log=$LOGS_DIR/fbv.log
else
	log=/dev/null
fi

out=${image}
# if ImageMagick's convert is installed, use it
if [ ! -z `command -v convert` ]; then
	# perhaps we want to cycle through different backgrounds?
	if [ -f $RES_DIR/bg_num.var ]; then
		read bg_num < $RES_DIR/bg_num.var
	else
		bg_num=1
	fi
	bg_list=$(identify -format "%d/%f:" $RES_DIR/backgrounds/* 2>/dev/null)
	background=$(echo ${bg_list} | cut -d':' -f ${bg_num})
	if [ -e "$background" ]; then
		bg_cmd="\\( mpr:img -fuzz 45% -transparent \#00ff00 +write mpr:img \\) \
			\\( \"${background}\" mpr:img -gravity center -composite +write mpr:img \\)"
	fi
	bg_num=$((bg_num+1))
	next=$(echo ${bg_list} | cut -d':' -f ${bg_num})
	if [ -z "${next}" ] || [ ! -f "${next}" ]; then
		bg_num=1
	fi
	echo ${bg_num} > $RES_DIR/bg_num.var

	logo=$RES_DIR/logo.png
	if [ -e $logo ]; then
		logo_cmd="\\( mpr:img $logo -gravity southeast -composite +write mpr:img \\)"
	fi
	if [ "$bg_cmd" != "" ] || [ "$logo_cmd" != "" ]; then
		out=${image}.out.jpg
		cmd="convert ${image} -write mpr:img +delete \
			$bg_cmd \
			$logo_cmd \
			\( mpr:img +write ${out} \) \
			NULL:"
		eval $cmd
	fi
fi

# if fbv is installed, use it
if [ -e /usr/local/bin/fbv ]; then
	cat /dev/zero > /dev/fb0 2>/dev/null;
	/usr/local/bin/fbv -quickfe $out 2>&1 >> $log
else
	# gThumg needs to be configured to enable Preferences->"Reuse the active window to open files"
	gthumb ${out} &
fi
