#!/bin/sh

export LANG=c

image=$1
LOGS_DIR=$2

if [ "$LOGS_DIR" != "" ] && [ -d $LOGS_DIR ]]; then
	log=$LOGS_DIR/fbv.log
else
	log=/dev/null
fi

if [ $some_variable == always_fail_for_now ]; then
	cat /dev/zero > /dev/fb0 2>/dev/null;
	/usr/local/bin/fbv -quickfe $image 2>&1 >> $log
else
	# we should already be showing final.png with gthumb
	FZ=45
	COL=\#00ff00
	convert ${image} -write mpr:AB +delete -respect-parentheses \( mpr:AB -fuzz ${FZ}% -transparent ${COL} +write mpr:CD \) \( background.jpg mpr:CD -gravity center -composite +write final.png \) \)

fi
